### ISSUE TITLE
Different .dng tags

### ISSUE THREAD

**Issue by vvubbalubba** [Jamy-L/Handheld-Multi-Frame-Super-Resolution#22]
Hi!
I'm trying to use this method for my own photos in .dng format, but i have 

Traceback (most recent call last):
  File "/home/jovyan/fominaav/Multi-frame-SR/Handheld-Multi-Frame-Super-Resolution/run_handheld.py", line 176, in <module>
    handheld_output = process(args.impath, options, params)
  File "/home/jovyan/fominaav/Multi-frame-SR/Handheld-Multi-Frame-Super-Resolution/handheld_super_resolution/super_resolution.py", line 325, in process
    ref_raw, raw_comp, ISO, tags, CFA, xyz2cam, ref_path = load_dng_burst(burst_path)
  File "/home/jovyan/fominaav/Multi-frame-SR/Handheld-Multi-Frame-Super-Resolution/handheld_super_resolution/utils_dng.py", line 85, in load_dng_burst
    white_level = tags['Image Tag 0xC61D'].values[0]  # there is only one white level
KeyError: 'Image Tag 0xC61D'

I checked the tags in your .dng-s and mine - they are different. Is there amy tool to fix it?

**Comment by Jamy-L** [comment]
Hi, 

It is very likely that the camera manufacter of your .dng's has put the whitebalance tag somewhere else. If your images display properly in regular image viewers, it probably means that the error is on our side.

I have just pushed a fix in which the reading is done using rawpy, which should be more robust to that. Please let me know if the issue still persists

**Comment by Jamy-L** [comment]
I have pushed a fix for the black level reading and the CFA. Problems may still occur for the ISO and for the noise profile, which cannot be read using rapy. Please let me know if any issue persists
